# Generated by Django 2.0.3 on 2018-05-07 21:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seckill', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('address', models.CharField(max_length=250, verbose_name='地址')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='邮编')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='城市')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', '生成'), ('0', '取消'), ('2', '待支付'), ('3', '已支付'), ('3', '退款'), ('4', '评价')], default=1, max_length=1, verbose_name='状态')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='金额')),
                ('coupon', models.CharField(blank=True, max_length=20, null=True, verbose_name='优惠券')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='折扣')),
                ('reply_dump', models.CharField(blank=True, max_length=500, null=True, verbose_name='支付信息')),
                ('reference_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='支付单号')),
                ('user', models.ForeignKey(on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete='', related_name='items', to='orders.Order')),
                ('product', models.ForeignKey(on_delete='', to='seckill.SaleProducts')),
            ],
        ),
    ]
