# 1.登陆
MODULE_CONFIG_LOGIN = 1

# 2.人员权限管理
# 21.角色
# 22.人员

# 3.产品管理
# 31.产品——产品
MODULE_CONFIG_PRODUCT_PRODUCT = 'PRODUCT_PRODUCT'
# 32.运维——服务器
MOUDLE_CONFIG_PRODUNCT_SERVER = 32
# 33.运维——服务租
MOUDLE_CONFIG_PRODUNCT_GROUP = 33
# 34.运维——节点
MOUDLE_CONFIG_PRODUNCT_GROUP = 34
