# Generated by Django 2.0.3 on 2019-01-28 07:39

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='广告标题')),
                ('description', models.CharField(max_length=200, verbose_name='广告描述')),
                ('image', models.ImageField(upload_to='ad/%Y/%m', verbose_name='图片路径')),
                ('callback_url', models.URLField(blank=True, null=True, verbose_name='回调url')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('index', models.IntegerField(default=999, verbose_name='排列顺序(从小到大)')),
                ('location', models.CharField(max_length=50, verbose_name='广告位置')),
                ('is_display', models.BooleanField(default=False, verbose_name='是否显示')),
                ('bgcolor', models.CharField(max_length=20, verbose_name='背景色')),
            ],
            options={
                'verbose_name_plural': '广告',
                'verbose_name': '广告',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BrowseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='名称')),
                ('slug', models.SlugField(default='', max_length=200, unique=True, verbose_name='标签')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('1', '正常'), ('0', '冻结')], db_index=True, default=1, max_length=1, verbose_name='状态')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='up_category', to='shop.Category', verbose_name='上级分类')),
            ],
            options={
                'verbose_name_plural': '分类表',
                'verbose_name': '分类表',
            },
        ),
        migrations.CreateModel(
            name='Categoryproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayname', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.CharField(blank=True, max_length=800, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
            options={
                'verbose_name_plural': '分类扩展属性表',
                'verbose_name': '分类扩展属性表',
            },
        ),
        migrations.CreateModel(
            name='Categorypropertyvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuename', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.CharField(blank=True, max_length=800, null=True)),
                ('categoryproperty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Categoryproperty')),
            ],
            options={
                'verbose_name_plural': '分类扩展属性值表',
                'verbose_name': '分类扩展属性值表',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='标签')),
                ('description', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('productno', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='编号')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='小图')),
                ('largeimage', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='大图')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价')),
                ('saleprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='销售价')),
                ('stock', models.PositiveIntegerField(verbose_name='库存')),
                ('available', models.BooleanField(default=True, verbose_name='有效')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=400, null=True, verbose_name='简要介绍')),
                ('viewnum', models.IntegerField(default=0, verbose_name='浏览数')),
                ('salenum', models.IntegerField(default=0, verbose_name='销售数')),
                ('commentnum', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='好评')),
                ('status', models.IntegerField(choices=[(1, '上架'), (0, '下架')], default=1, verbose_name='状态')),
                ('unit', models.CharField(blank=True, max_length=200, null=True, verbose_name='单位')),
                ('spec', models.CharField(blank=True, max_length=200, null=True, verbose_name='规格')),
                ('sale_num', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='销售量')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Productpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picurl', models.ImageField(blank=True, upload_to='product/%Y/%m/%d', verbose_name='图片')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='Productproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('categoryproperty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Categoryproperty')),
                ('categorypropertyvalue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Categorypropertyvalue')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            options={
                'verbose_name_plural': '商品扩展属性',
                'verbose_name': '商品扩展属性',
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiredate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='有效期')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=800, null=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('1', '正常'), ('0', '冻结')], db_index=True, default=1, max_length=1, verbose_name='状态')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='商品')),
            ],
            options={
                'verbose_name_plural': '新品推荐',
                'verbose_name': '新品推荐',
            },
        ),
        migrations.CreateModel(
            name='Saleproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.CharField(blank=True, max_length=800, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
            options={
                'verbose_name_plural': '分类销售属性表',
                'verbose_name': '分类销售属性表',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='名称')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机')),
                ('linkman', models.CharField(blank=True, max_length=200, null=True, verbose_name='联系人')),
                ('desc', models.CharField(blank=True, max_length=800, null=True, verbose_name='介绍')),
                ('address', models.CharField(blank=True, max_length=800, null=True, verbose_name='地址')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(db_index=True, default=1, max_length=1, verbose_name='状态')),
                ('appid', models.CharField(blank=True, max_length=200, null=True, verbose_name='appid')),
                ('remark', models.CharField(blank=True, max_length=800, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '店主',
                'verbose_name': '店主',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='名称')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('linkman', models.CharField(blank=True, max_length=200, null=True, verbose_name='联系人')),
                ('desc', models.CharField(blank=True, max_length=800, null=True, verbose_name='介绍')),
                ('kind', models.CharField(choices=[('1', '手机通讯'), ('2', '电脑数码'), ('3', '家用电器'), ('4', '服饰鞋包'), ('5', '厨房卫浴'), ('6', '家居家装')], db_index=True, default=1, max_length=2, verbose_name='类别')),
                ('brands', models.CharField(blank=True, max_length=50, null=True, verbose_name='品牌')),
                ('image', models.ImageField(blank=True, upload_to='supplier/', verbose_name='图片')),
                ('styimg', models.ImageField(blank=True, upload_to='supplier/', verbose_name='主款图片')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('1', '正常'), ('0', '冻结')], db_index=True, default=1, max_length=1, verbose_name='状态')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
            options={
                'verbose_name_plural': 'suppliers',
                'verbose_name': '供应商',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='supplier',
            field=models.ManyToManyField(to='shop.Supplier'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='product',
            name='saleproperty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Saleproperty', verbose_name='销售标识'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Store', verbose_name='店主'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='browsehistory',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='所述商品'),
        ),
        migrations.AddField(
            model_name='browsehistory',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
