# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workorder_manage', '0006_auto_20171129_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, help_text='是否可用')),
                ('avatar', models.URLField(help_text='接待组显示头像地址')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteReceptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, help_text='是否可用')),
                ('title', models.CharField(help_text='接待组名称', max_length=20)),
                ('group_id', models.CharField(help_text='接待组ID', max_length=100)),
                ('manager', models.CharField(help_text='接待经理', max_length=20)),
                ('phone_number', models.CharField(help_text='电话', max_length=20)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('desc', models.CharField(help_text='一句话介绍', max_length=100)),
                ('url', models.URLField(help_text='网址')),
                ('site', models.OneToOneField(help_text='关联站点', on_delete=django.db.models.deletion.CASCADE, to='workorder_manage.StationInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='receptionavatar',
            name='reception_group',
            field=models.ForeignKey(blank=True, help_text='对应接待组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='setup.SiteReceptionGroup'),
        ),
    ]
