# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionavatar',
            name='reception_group',
        ),
        migrations.AddField(
            model_name='sitereceptiongroup',
            name='avatar',
            field=models.URLField(default='', help_text='显示头像'),
        ),
        migrations.DeleteModel(
            name='ReceptionAvatar',
        ),
    ]
