# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20171205_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitereceptiongroup',
            options={'permissions': (('view_site_reception_group', 'Can see available site_reception_group'),)},
        ),
    ]
