# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_auto_20171214_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitereceptiongroup',
            options={'permissions': (('view_sitereceptiongroup', 'Can see available site_reception_group'),)},
        ),
    ]
