# Generated by Django 2.0.3 on 2019-01-28 07:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(default='', max_length=30, verbose_name='区县code')),
                ('area', models.CharField(default='', max_length=50, verbose_name='区县')),
                ('city_code', models.CharField(default='', max_length=30, verbose_name='市code')),
            ],
            options={
                'verbose_name_plural': '区县',
                'verbose_name': '区县',
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(default='', max_length=30, verbose_name='市code')),
                ('city', models.CharField(default='', max_length=50, verbose_name='市')),
                ('province_code', models.CharField(default='', max_length=30, verbose_name='省份code')),
            ],
            options={
                'verbose_name_plural': '市',
                'verbose_name': '市',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True, verbose_name='头像')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('O', '秘密')], default='O', max_length=6, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('score', models.IntegerField(default=0, verbose_name='积分')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_code', models.CharField(default='', max_length=30, verbose_name='省份code')),
                ('province', models.CharField(default='', max_length=50, verbose_name='省份')),
            ],
            options={
                'verbose_name_plural': '省',
                'verbose_name': '省',
                'db_table': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=100, verbose_name='详细地址')),
                ('signername', models.CharField(default='', max_length=100, verbose_name='签收人')),
                ('post', models.CharField(default='', max_length=6, verbose_name='邮编')),
                ('mobile', models.CharField(default='', max_length=11, verbose_name='手机')),
                ('tel', models.CharField(default='', max_length=11, verbose_name='电话')),
                ('flag', models.CharField(default='1', max_length=2, verbose_name='是否默认地址')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Areas', verbose_name='区县')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Cities', verbose_name='市')),
                ('provinces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Provinces', verbose_name='省')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '收货地址',
                'verbose_name': '收货地址',
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('products', models.ForeignKey(help_text='商品id', on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户收藏',
                'verbose_name': '用户收藏',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagetype', models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '询问'), (4, '售后')], default=1, help_text='留言类型: 1(留言),2(投诉),3(询问),4(售后)', verbose_name='留言类型')),
                ('subject', models.CharField(default='', max_length=100, verbose_name='主题')),
                ('message', models.TextField(default='', help_text='留言内容', verbose_name='留言内容')),
                ('file', models.FileField(help_text='上传的文件', upload_to='message/', verbose_name='上传的文件')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('senduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senduser', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户留言',
                'verbose_name': '用户留言',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together={('user', 'products')},
        ),
    ]
