# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(max_length=100)),
                ('db_address', models.CharField(max_length=500)),
                ('db_name', models.CharField(max_length=100)),
                ('db_username', models.CharField(max_length=100)),
                ('db_pwd', models.CharField(max_length=100)),
                ('db_port', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '数据库信息',
                'verbose_name_plural': '数据库信息',
                'permissions': (('view_databaseinfo', 'Can see available data base info'),),
            },
        ),
        migrations.CreateModel(
            name='FunctionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_name', models.CharField(max_length=100)),
                ('cli_version', models.IntegerField(choices=[(1, 'B2B'), (2, 'B2C'), (3, '不限')])),
                ('func_code', models.CharField(max_length=100)),
                ('func_type', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '功能信息',
                'verbose_name_plural': '功能信息',
            },
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_name', models.CharField(max_length=100, unique=True)),
                ('grid_site', models.CharField(max_length=50)),
                ('deploy_way', models.IntegerField()),
            ],
            options={
                'verbose_name': '节点信息',
                'verbose_name_plural': '节点信息',
                'permissions': (('view_grid', 'Can see available grids'),),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '产品名称',
                'verbose_name_plural': '产品名称',
                'ordering': ['id'],
                'permissions': (('view_product', 'Can see available products'),),
            },
        ),
        migrations.CreateModel(
            name='SerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '服务地址',
                'verbose_name_plural': '服务地址',
                'permissions': (('view_seraddress', 'Can see available ser address'),),
            },
        ),
        migrations.CreateModel(
            name='SerIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_ip', models.CharField(max_length=50)),
                ('ser_address', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ser_ip', to='production_manage.SerAddress')),
            ],
            options={
                'verbose_name': '服务器IP',
                'verbose_name_plural': '服务器IP',
            },
        ),
        migrations.CreateModel(
            name='SerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_type', models.CharField(max_length=50, unique=True)),
                ('cor_product', models.ManyToManyField(db_constraint=False, related_name='sertype', to='production_manage.Product')),
            ],
            options={
                'verbose_name': '服务类型',
                'verbose_name_plural': '服务类型',
                'permissions': (('view_sertype', 'Can see available ser type'),),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_id', models.CharField(max_length=100, unique=True)),
                ('ser_version', models.CharField(max_length=30)),
                ('ser_name', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server', to='production_manage.SerType')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
                'permissions': (('view_server', 'Can see available servers'),),
            },
        ),
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('grid', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='production_manage.Grid')),
                ('ser_address', models.ManyToManyField(db_constraint=False, related_name='group', to='production_manage.SerAddress')),
            ],
            options={
                'verbose_name': '服务组信息',
                'verbose_name_plural': '服务组信息',
                'permissions': (('view_servergroup', 'Can see available servergroups'),),
            },
        ),
        migrations.CreateModel(
            name='SingleSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_name', models.CharField(max_length=100)),
                ('select_value', models.CharField(max_length=100)),
                ('function', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selection', to='production_manage.FunctionInfo')),
            ],
            options={
                'verbose_name': '功能开关',
                'verbose_name_plural': '功能开关',
                'permissions': (('view_singleselection', 'Can see available single selection'),),
            },
        ),
        migrations.CreateModel(
            name='VersionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_version', models.CharField(max_length=30)),
                ('product', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version', to='production_manage.Product')),
            ],
            options={
                'verbose_name': '版本信息',
                'verbose_name_plural': '版本信息',
                'permissions': (('view_versioninfo', 'Can see available versioninfos'),),
            },
        ),
        migrations.AddField(
            model_name='seraddress',
            name='server',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ser_url', to='production_manage.Server'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('id', 'product')]),
        ),
        migrations.AddField(
            model_name='grid',
            name='versionInfos',
            field=models.ManyToManyField(db_constraint=False, related_name='grid', to='production_manage.VersionInfo'),
        ),
        migrations.AddField(
            model_name='functioninfo',
            name='version',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='function', to='production_manage.VersionInfo'),
        ),
        migrations.AddField(
            model_name='databaseinfo',
            name='grid',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_info', to='production_manage.Grid'),
        ),
    ]
