# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='functioninfo',
            name='is_enable',
            field=models.BooleanField(default=True, help_text='是否可用'),
        ),
        migrations.AddField(
            model_name='grid',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='创建时间'),
        ),
        migrations.AddField(
            model_name='grid',
            name='is_enable',
            field=models.BooleanField(default=True, help_text='是否可用'),
        ),
        migrations.AddField(
            model_name='grid',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='更新时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='创建时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_enable',
            field=models.BooleanField(default=True, help_text='是否可用'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='更新时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='创建时间'),
        ),
        migrations.AddField(
            model_name='server',
            name='is_enable',
            field=models.BooleanField(default=True, help_text='是否可用'),
        ),
        migrations.AddField(
            model_name='server',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='更新时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servergroup',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='创建时间'),
        ),
        migrations.AddField(
            model_name='servergroup',
            name='is_enable',
            field=models.BooleanField(default=True, help_text='是否可用'),
        ),
        migrations.AddField(
            model_name='servergroup',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='更新时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singleselection',
            name='is_enable',
            field=models.BooleanField(default=True, help_text='是否可用'),
        ),
        migrations.AddField(
            model_name='versioninfo',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='创建时间'),
        ),
        migrations.AddField(
            model_name='versioninfo',
            name='is_enable',
            field=models.BooleanField(default=True, help_text='是否可用'),
        ),
        migrations.AddField(
            model_name='versioninfo',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='更新时间'),
            preserve_default=False,
        ),
    ]
