# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0002_auto_20171011_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleselection',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
