# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0003_singleselection_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleselection',
            name='is_default',
        ),
        migrations.AddField(
            model_name='functioninfo',
            name='default_selc',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_manage.SingleSelection'),
        ),
    ]
