# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0004_auto_20171017_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functioninfo',
            name='default_selc',
        ),
        migrations.AddField(
            model_name='singleselection',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
