# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0006_remove_server_ser_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseinfo',
            name='db_pwd',
            field=models.CharField(help_text='加密后的密码', max_length=100),
        ),
        migrations.AlterField(
            model_name='databaseinfo',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_info', to='production_manage.Grid'),
        ),
    ]
