# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0009_auto_20171030_1951'),
        ('production_manage', '0007_auto_20171101_1013'),
    ]

    operations = [
    ]
