# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0010_deployway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployway',
            name='deploy_way',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
