# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0010_merge_20171101_1036'),
        ('production_manage', '0011_auto_20171101_1353'),
    ]

    operations = [
    ]
