# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0012_merge_20171101_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeployWay',
        ),
    ]
