# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0014_auto_20171123_1721'),
        ('production_manage', '0014_auto_20171123_1646'),
    ]

    operations = [
    ]
