# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0015_merge_20171124_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='version_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='version_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servergroup',
            name='version_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
