# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0016_auto_20171222_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('view_product', 'Can see available products'),), 'verbose_name': '产品名称', 'verbose_name_plural': '产品名称'},
        ),
        migrations.RemoveField(
            model_name='functioninfo',
            name='version',
        ),
        migrations.AddField(
            model_name='functioninfo',
            name='dependences',
            field=models.ManyToManyField(db_constraint=False, related_name='relatedfunc', to='production_manage.SingleSelection'),
        ),
        migrations.AddField(
            model_name='functioninfo',
            name='parent',
            field=models.ManyToManyField(db_constraint=False, related_name='childfunc', to='production_manage.SingleSelection'),
        ),
        migrations.AddField(
            model_name='functioninfo',
            name='product',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='function', to='production_manage.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='classify',
            field=models.SmallIntegerField(choices=[(2, '重构版'), (1, '经典版')], default=1, help_text='产品类别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sertype',
            name='version_type',
            field=models.SmallIntegerField(choices=[(2, '重构版'), (1, '经典版')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versioninfo',
            name='function',
            field=models.ManyToManyField(db_constraint=False, related_name='version', to='production_manage.FunctionInfo'),
        ),
        migrations.AlterField(
            model_name='grid',
            name='version_type',
            field=models.SmallIntegerField(choices=[(2, '重构版'), (1, '经典版')]),
        ),
        migrations.AlterField(
            model_name='server',
            name='version_type',
            field=models.SmallIntegerField(choices=[(2, '重构版'), (1, '经典版')]),
        ),
        migrations.AlterField(
            model_name='servergroup',
            name='version_type',
            field=models.SmallIntegerField(choices=[(2, '重构版'), (1, '经典版')]),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([]),
        ),
    ]
