# Generated by Django 2.0.3 on 2018-05-07 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='1', max_length=1, verbose_name='状态')),
                ('lockdate', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d', verbose_name='图')),
                ('score', models.IntegerField(default=0, verbose_name='积分')),
                ('grender', models.CharField(default='o', max_length=1, verbose_name='性别')),
                ('address', models.CharField(default='', max_length=200, verbose_name='地址')),
                ('email', models.CharField(default='', max_length=30, verbose_name='邮箱')),
                ('moible', models.CharField(default='', max_length=15, verbose_name='手机')),
                ('user', models.OneToOneField(on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
