# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0002_auto_20171011_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='abbreviation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
