# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0004_auto_20171121_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountconf',
            name='set_pwd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
