# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0015_merge_20171124_1644'),
        ('workorder_manage', '0005_auto_20171122_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='server_grp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_manage.ServerGroup'),
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='deploy_way',
            field=models.IntegerField(choices=[(1, '标准版'), (2, 'VIP版'), (3, 'VPC版'), (4, '企业版')]),
        ),
    ]
