# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0006_auto_20171129_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='创建时间'),
        ),
        migrations.AddField(
            model_name='industry',
            name='is_enable',
            field=models.BooleanField(default=True, help_text='是否可用'),
        ),
        migrations.AddField(
            model_name='industry',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='更新时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='industry',
            field=models.CharField(max_length=60),
        ),
    ]
