# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0008_auto_20171214_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='classify',
            field=models.SmallIntegerField(choices=[(2, '重构版'), (1, '经典版')], default=1, help_text='产品类别'),
            preserve_default=False,
        ),
    ]
