# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('operationtime', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=20, null=True)),
                ('action', models.IntegerField(choices=[(1, '新增'), (2, '删除'), (3, '修改'), (4, '查看'), (5, '检索')], null=True)),
                ('operationmodule', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
