# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_manage', '0002_auto_20171011_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatelog',
            name='action',
            field=models.IntegerField(choices=[(1, '新增'), (2, '删除'), (3, '修改'), (500, '其他'), (4, '登录'), (5, '退出')], null=True),
        ),
    ]
