# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_manage', '0003_auto_20171012_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatelog',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, '新增'), (2, '删除'), (3, '修改'), (500, '其他'), (4, '登录'), (5, '退出')], null=True),
        ),
        migrations.AlterField(
            model_name='operatelog',
            name='operation',
            field=models.TextField(null=True),
        ),
    ]
