# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_manage', '0004_auto_20171012_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatelog',
            options={'permissions': (('view_system_log', 'Can see available system log'), ('view_personal_log', 'Can see available personal log'))},
        ),
        migrations.AlterField(
            model_name='operatelog',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, '新增'), (2, '删除'), (3, '修改'), (4, '登录'), (5, '退出'), (500, '其他')], null=True),
        ),
    ]
