# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_manage', '0005_auto_20171013_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatelog',
            options={'permissions': (('view_system-log', 'Can see available system log'), ('view_personal-log', 'Can see available personal log'))},
        ),
    ]
