# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InquiriesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(help_text='所属行业', max_length=60)),
                ('deploy_way', models.SmallIntegerField(choices=[(1, '标准版'), (2, 'VIP版'), (3, 'VPC版本'), (4, '企业版')], help_text='部署方式')),
                ('cli_version', models.SmallIntegerField(choices=[(1, 'B2B'), (2, 'B2C'), (3, '不限')], help_text='客户版本')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='更新时间')),
                ('date', models.DateField(help_text='记录时间')),
                ('company_id', models.CharField(help_text='站点ID', max_length=50)),
                ('channel', models.SmallIntegerField(choices=[(0, 'PC'), (1, '微信'), (2, 'APP'), (3, 'WAP'), (4, 'IOS'), (5, 'Android'), (-1, '未知'), (7, '微博'), (8, 'QQ')], help_text='渠道类别')),
                ('inquires_num', models.IntegerField(default=0, help_text='咨询量')),
            ],
            options={
                'verbose_name': '渠道别咨询量记录',
                'verbose_name_plural': '渠道别咨询量记录',
            },
        ),
        migrations.CreateModel(
            name='OnlineClientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(help_text='所属行业', max_length=60)),
                ('deploy_way', models.SmallIntegerField(choices=[(1, '标准版'), (2, 'VIP版'), (3, 'VPC版本'), (4, '企业版')], help_text='部署方式')),
                ('cli_version', models.SmallIntegerField(choices=[(1, 'B2B'), (2, 'B2C'), (3, '不限')], help_text='客户版本')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='更新时间')),
                ('date', models.DateField(help_text='记录时间')),
                ('online_num', models.IntegerField(default=0, help_text='在线客户数量')),
            ],
            options={
                'verbose_name': '在线客户数量',
                'verbose_name_plural': '在线客户数量',
            },
        ),
        migrations.CreateModel(
            name='OnlineProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(help_text='所属行业', max_length=60)),
                ('deploy_way', models.SmallIntegerField(choices=[(1, '标准版'), (2, 'VIP版'), (3, 'VPC版本'), (4, '企业版')], help_text='部署方式')),
                ('cli_version', models.SmallIntegerField(choices=[(1, 'B2B'), (2, 'B2C'), (3, '不限')], help_text='客户版本')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='更新时间')),
                ('date', models.DateField(help_text='记录时间')),
                ('online_num', models.IntegerField(default=0, help_text='在线客户使用产品数量')),
                ('product_id', models.CharField(help_text='产品ID', max_length=50)),
            ],
            options={
                'verbose_name': '在线产品使用数量',
                'verbose_name_plural': '在线产品使用数量',
            },
        ),
    ]
