# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=30, unique=True)),
                ('channel_no', models.IntegerField()),
            ],
        ),
    ]
