# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0003_delete_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiriesdata',
            name='channel',
            field=models.SmallIntegerField(choices=[(6, 'PC'), (1, '微信'), (2, 'APP'), (3, 'WAP'), (4, 'IOS'), (5, 'Android'), (-1, '未知'), (7, '微博'), (8, 'QQ')], help_text='渠道类别'),
        ),
    ]
