# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0005_operatingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiriesdata',
            name='server_grp',
            field=models.CharField(blank=True, help_text='服务组', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inquiriesdata',
            name='deploy_way',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, 'VIP版'), (3, 'VPC版'), (4, '企业版')], help_text='部署方式'),
        ),
        migrations.AlterField(
            model_name='onlineclientdata',
            name='deploy_way',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, 'VIP版'), (3, 'VPC版'), (4, '企业版')], help_text='部署方式'),
        ),
        migrations.AlterField(
            model_name='onlineproductdata',
            name='deploy_way',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, 'VIP版'), (3, 'VPC版'), (4, '企业版')], help_text='部署方式'),
        ),
        migrations.AlterField(
            model_name='operatingrecord',
            name='deploy_way',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, 'VIP版'), (3, 'VPC版'), (4, '企业版')], help_text='部署方式'),
        ),
    ]
