# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0006_auto_20171129_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiriesdata',
            options={'permissions': (('view_overview_data', '查看咨询量'),), 'verbose_name': '渠道别咨询量记录', 'verbose_name_plural': '渠道别咨询量记录'},
        ),
        migrations.AlterModelOptions(
            name='operatingrecord',
            options={'permissions': (('view_ops_data', '查看运营记录'), ('view_prod_oper_data', '查看产品运营记录')), 'verbose_name': '运营记录', 'verbose_name_plural': '运营记录'},
        ),
    ]
