# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0007_auto_20171214_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiriesdata',
            options={'permissions': (('view_overview-data', '查看咨询量'),), 'verbose_name': '渠道别咨询量记录', 'verbose_name_plural': '渠道别咨询量记录'},
        ),
        migrations.AlterModelOptions(
            name='operatingrecord',
            options={'permissions': (('view_ops-data', '查看运营记录'), ('view_prod-oper-data', '查看产品运营记录')), 'verbose_name': '运营记录', 'verbose_name_plural': '运营记录'},
        ),
    ]
