# Generated by Django 2.0.3 on 2018-05-07 21:32

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='名称')),
                ('slug', models.SlugField(default='', max_length=200, unique=True, verbose_name='标签')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('1', '正常'), ('0', '冻结')], db_index=True, default=1, max_length=1, verbose_name='状态')),
                ('parent', models.ForeignKey(blank=True, default=0, null=True, on_delete='', related_name='child', to='seckill.Category', verbose_name='上级分类')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'verbose_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='标签')),
                ('description', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('productno', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='编号')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='小图')),
                ('largeimage', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='大图')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价')),
                ('saleprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='销售价')),
                ('stock', models.PositiveIntegerField(verbose_name='库存')),
                ('available', models.BooleanField(default=True, verbose_name='有效')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=400, null=True, verbose_name='简要介绍')),
                ('category', models.ForeignKey(on_delete='', to='seckill.Category')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SaleProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('status', models.CharField(blank=True, choices=[('1', '正常'), ('0', '冻结'), ('2', '过期')], max_length=1, null=True, verbose_name='状态')),
                ('marketprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='市场价')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='秒杀价')),
                ('startdatetime', models.DateTimeField(default=datetime.datetime(2018, 5, 7, 21, 31, 59, 938869), verbose_name='开始时间')),
                ('enddatetime', models.DateTimeField(default=datetime.datetime(2018, 5, 7, 22, 31, 59, 937868), verbose_name='结束时间')),
                ('stock_total', models.IntegerField(default=0, verbose_name='总库存')),
                ('remain_qty', models.IntegerField(default=0, verbose_name='可销售数')),
                ('desc', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='小图')),
                ('protduct', models.ForeignKey(blank=True, null=True, on_delete='', to='seckill.Product', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='名称')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('linkman', models.CharField(blank=True, max_length=200, null=True, verbose_name='联系人')),
                ('desc', models.CharField(blank=True, max_length=800, null=True, verbose_name='介绍')),
                ('kind', models.CharField(choices=[('1', '供货商'), ('1', '物流公司'), ('2', '其他')], db_index=True, default=1, max_length=2, verbose_name='类别')),
                ('brands', models.CharField(blank=True, max_length=50, null=True, verbose_name='品牌')),
                ('image', models.ImageField(blank=True, upload_to='supplier/', verbose_name='图片')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('1', '正常'), ('0', '冻结')], db_index=True, default=1, max_length=1, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': 'suppliers',
                'verbose_name': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Ziku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qustion', models.CharField(blank=True, max_length=200, null=True, verbose_name='问题')),
                ('answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='答案')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete='', to='seckill.Supplier', verbose_name='供应商'),
        ),
    ]
