# Generated by Django 2.0.3 on 2019-01-28 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, verbose_name='兑换码')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='说明')),
                ('percentage_discount', models.IntegerField(default=0, verbose_name='优惠折扣')),
                ('preamount', models.IntegerField(default=0, verbose_name='优惠金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('type', models.CharField(choices=[(1, '单一商品'), (2, '全部商品')], db_index=True, default=1, max_length=2, verbose_name='类型')),
                ('maxnum', models.IntegerField(blank=True, null=True, verbose_name='最大数量')),
                ('remark', models.CharField(blank=True, db_index=True, max_length=400, null=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product')),
            ],
            options={
                'verbose_name': '优惠券主表',
                'verbose_name_plural': '优惠券主表',
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usedate', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('getdate', models.DateTimeField(blank=True, null=True, verbose_name='领用时间')),
                ('status', models.CharField(choices=[('1', '有效'), ('2', '已使用'), ('3', '失效'), ('4', '删除')], db_index=True, default=1, max_length=2, verbose_name='状态')),
                ('percentage_discount', models.IntegerField(default=0, verbose_name='优惠折扣')),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.Coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '优惠券明细表',
                'verbose_name_plural': '优惠券明细表',
            },
        ),
    ]
