# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_user', '0001_initial'),
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goods_count', models.IntegerField(default=1, verbose_name='商品数目')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.Goods', verbose_name='商品名称')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.Passport', verbose_name='账户名称')),
            ],
            options={
                'db_table': 's_cart',
            },
        ),
    ]
