# Generated by Django 2.0.3 on 2019-01-28 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '支付成功'), (2, '已退款'), (3, '取消')], default=1, verbose_name='状态')),
                ('paytime', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('desc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='支付信息')),
                ('payno', models.CharField(blank=True, max_length=40, null=True, verbose_name='支付单号')),
                ('paytype', models.SmallIntegerField(blank=True, choices=[(1, '微信支付'), (2, '支付宝'), (3, '银联支付')], null=True, verbose_name='支付类型')),
                ('payamount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='支付金额')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '支付信息',
            },
        ),
    ]
